"""Add a new attribute  in the JobBoards Model

Revision ID: adab23d356d3
Revises: 4926cebb3697
Create Date: 2025-11-24 16:33:44.089721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adab23d356d3'
down_revision: Union[str, Sequence[str], None] = '4926cebb3697'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_boards', sa.Column('logo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_boards', 'logo_url')
    # ### end Alembic commands ###
