"""add close_date to job_posts

Revision ID: ff6985671361
Revises: ac417b7888f2
Create Date: 2025-11-26 09:03:07.324337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff6985671361'
down_revision: Union[str, Sequence[str], None] = 'ac417b7888f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_posts', sa.Column('close_date', sa.Date(), nullable=True))
    op.drop_column('job_posts', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_posts', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('job_posts', 'close_date')
    # ### end Alembic commands ###
